<template>
  <meting-js
    id="7461758096"
    server="netease"
    type="playlist"
    fixed="false"
    autoplay="false"
    loop="all"
    order="list"
    preload="auto"
    list-folded="false"
    list-max-height="98px"
    lrc-type="1"
  />
</template>
