// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert/index.vue')['default']
    Article: typeof import('./src/components/Article/index.vue')['default']
    Catalogue: typeof import('./src/components/Catalogue/index.vue')['default']
    Disqus: typeof import('./src/components/Disqus/index.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElImage: typeof import('element-plus/es')['ElImage']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftSide: typeof import('./src/components/leftSide/index.vue')['default']
    Map: typeof import('./src/components/map/index.vue')['default']
    Music: typeof import('./src/components/Music/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialDescr: typeof import('./src/components/SpecialDescr/index.vue')['default']
    SpecialModular: typeof import('./src/components/SpecialModular/index.vue')['default']
    UpperApex: typeof import('./src/components/UpperApex/index.vue')['default']
  }
}

export {}
